title: Center Path LLC
description: DevOps coaching and consulting

url: https://www.centerpath.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/
description: Level up your team's DevOps game with a software development mindset. Cloud automation, containers, CI/CD pipelines, Kubernetes and serverless workloads.

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-sitemap
paginate: 5

navigation:
  - title: DevOps Coaching &amp; Consulting
    url: /index.html

social:
  github: davekonopka
  twitter: davekonopka
  email: dave@centerpath.io

google_analytics: "UA-148343113-1"
